create table especies(
    id smallint not null,
    sigla char(3) not null,
    nome varchar(256) not null,
    primary key(id)
);

CREATE INDEX idx_especies_sigla ON especies (sigla ASC);

insert into especies (id, sigla, nome) values (0, 'ALL', '[Todos]');
insert into especies (id, sigla, nome) values (55, 'ADM', 'Processo Administrativo');
insert into especies (id, sigla, nome) values (180, 'ALV', 'Alvará');
insert into especies (id, sigla, nome) values (198, 'ATA', 'Ata');
insert into especies (id, sigla, nome) values (200, 'ATE', 'Atestado');
insert into especies (id, sigla, nome) values (184, 'ATN', 'Ato Normativo');
insert into especies (id, sigla, nome) values (199, 'AUT', 'Autorização');
insert into especies (id, sigla, nome) values (185, 'AVS', 'Aviso');
insert into especies (id, sigla, nome) values (54, 'BIE', 'Boletim Interno');
insert into especies (id, sigla, nome) values (201, 'BOL', 'Boletim');
insert into especies (id, sigla, nome) values (100, 'CAP', 'Documento Capturado');
insert into especies (id, sigla, nome) values (220, 'CAR', 'Carta');
insert into especies (id, sigla, nome) values (15, 'CER', 'Certidão');
insert into especies (id, sigla, nome) values (188, 'CLI', 'Clipping');
insert into especies (id, sigla, nome) values (186, 'COM', 'Comunicado');
insert into especies (id, sigla, nome) values (9, 'CON', 'Contrato');
insert into especies (id, sigla, nome) values (260, 'COV', 'Convite');
insert into especies (id, sigla, nome) values (203, 'CPV', 'Comprovante');
insert into especies (id, sigla, nome) values (187, 'CRO', 'Cronograma');
insert into especies (id, sigla, nome) values (340, 'CTC', 'Certidão de Tempo de Contribuição');
insert into especies (id, sigla, nome) values (181, 'CTF', 'Certificado');
insert into especies (id, sigla, nome) values (221, 'CVC', 'Convocação');
insert into especies (id, sigla, nome) values (360, 'DCI', 'Documento Capturado Interno');
insert into especies (id, sigla, nome) values (223, 'DCT', 'Decreto');
insert into especies (id, sigla, nome) values (222, 'DEC', 'Declaração');
insert into especies (id, sigla, nome) values (209, 'DEL', 'Deliberação');
insert into especies (id, sigla, nome) values (241, 'DEM', 'Demonstrativo');
insert into especies (id, sigla, nome) values (8, 'DES', 'Despacho');
insert into especies (id, sigla, nome) values (208, 'DOS', 'Dossiê');
insert into especies (id, sigla, nome) values (420, 'EDF', 'Escala de férias');
insert into especies (id, sigla, nome) values (210, 'EDI', 'Edital');
insert into especies (id, sigla, nome) values (341, 'EME', 'Ementa');
insert into especies (id, sigla, nome) values (57, 'EOF', 'Processo de Execução Orçamentária e Financeira');
insert into especies (id, sigla, nome) values (205, 'ESC', 'Escala');
insert into especies (id, sigla, nome) values (140, 'EXP', 'Expediente');
insert into especies (id, sigla, nome) values (5, 'EXT', 'Externo');
insert into especies (id, sigla, nome) values (224, 'FIC', 'Ficha');
insert into especies (id, sigla, nome) values (3, 'FOR', 'Formulário');
insert into especies (id, sigla, nome) values (202, 'GUI', 'Guia');
insert into especies (id, sigla, nome) values (400, 'IND', 'Índice');
insert into especies (id, sigla, nome) values (4, 'INF', 'Informação');
insert into especies (id, sigla, nome) values (160, 'INS', 'Instrução');
insert into especies (id, sigla, nome) values (520, 'INT', 'Intimação');
insert into especies (id, sigla, nome) values (193, 'INV', 'Inventário');
insert into especies (id, sigla, nome) values (204, 'LAU', 'Laudo');
insert into especies (id, sigla, nome) values (280, 'LEI', 'Lei');
insert into especies (id, sigla, nome) values (196, 'LIS', 'Lista');
insert into especies (id, sigla, nome) values (120, 'MAN', 'Manifestação');
insert into especies (id, sigla, nome) values (189, 'MAT', 'Matéria');
insert into especies (id, sigla, nome) values (342, 'MCT', 'Minuta Certidão de Tempo de Contribuição');
insert into especies (id, sigla, nome) values (460, 'MDC', 'Mandado');
insert into especies (id, sigla, nome) values (2, 'MEM', 'Memorando');
insert into especies (id, sigla, nome) values (191, 'MIN', 'Minuta');
insert into especies (id, sigla, nome) values (380, 'MNL', 'Manual');
insert into especies (id, sigla, nome) values (97, 'MRU', 'Memória de Reunião');
insert into especies (id, sigla, nome) values (206, 'NOT', 'Nota');
insert into especies (id, sigla, nome) values (480, 'NTF', 'Notificação');
insert into especies (id, sigla, nome) values (1, 'OFI', 'Ofício');
insert into especies (id, sigla, nome) values (183, 'ORD', 'Ordem');
insert into especies (id, sigla, nome) values (14, 'PAR', 'Parecer');
insert into especies (id, sigla, nome) values (500, 'PIC', 'Parecer Capturado Interno');
insert into especies (id, sigla, nome) values (240, 'PJT', 'Projeto');
insert into especies (id, sigla, nome) values (192, 'PLA', 'Planilha');
insert into especies (id, sigla, nome) values (194, 'PLN', 'Plano');
insert into especies (id, sigla, nome) values (212, 'POR', 'Portaria');
insert into especies (id, sigla, nome) values (211, 'PRC', 'Processo');
insert into especies (id, sigla, nome) values (195, 'PRO', 'Programa');
insert into especies (id, sigla, nome) values (242, 'PRP', 'Proposta');
insert into especies (id, sigla, nome) values (197, 'PRT', 'Prontuário');
insert into especies (id, sigla, nome) values (182, 'REC', 'Recibo');
insert into especies (id, sigla, nome) values (540, 'REG', 'Regimento');
insert into especies (id, sigla, nome) values (98, 'REL', 'Relatório');
insert into especies (id, sigla, nome) values (12, 'REQ', 'Requerimento');
insert into especies (id, sigla, nome) values (190, 'RES', 'Resumo');
insert into especies (id, sigla, nome) values (56, 'RHU', 'Processo de Pessoal');
insert into especies (id, sigla, nome) values (320, 'RLA', 'Relação');
insert into especies (id, sigla, nome) values (225, 'RQS', 'Requisição');
insert into especies (id, sigla, nome) values (226, 'RSL', 'Resolução');
insert into especies (id, sigla, nome) values (13, 'SOL', 'Solicitação');
insert into especies (id, sigla, nome) values (207, 'SUM', 'Súmula');
insert into especies (id, sigla, nome) values (301, 'TAB', 'Tabela');
insert into especies (id, sigla, nome) values (300, 'TEE', 'Termo');
insert into especies (id, sigla, nome) values (227, 'TER', 'Termo');
insert into especies (id, sigla, nome) values (440, 'VTO', 'Voto');
